### ISSUE TITLE
При совпадении в юникодной строке должны выводиться индексы codepoint, а не байтов

### ISSUE THREAD

**Issue by mkpankov** [mkpankov/greprs#3]

**Comment by cblp** [comment]
Индексы символов не получится вычислить, только кодпойнтов.

**Comment by mkpankov** [comment]
@cblp подробности?

**Comment by cblp** [comment]
1. один символ может кодироваться разными последовательностями кодпойнтов разной длины
2. лигатура — один символ или несколько?
3. арабская вязь — несколько символов или вообще не символы?
4. диакритический знак — это вообще символ или не символ? он же не добавляет нового знакоместа при печати

и т. д.

**Comment by cblp** [comment]
даже "позиции, видимые на экране", даже в моноширинном шрифте нельзя посчитать в общем случае, потому что это от шрифта зависит

**Comment by mkpankov** [comment]
@cblp ок, можно сделать индексы codepoint'ов. Наш случай с русским языком это прекрасно покроет
